version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12
        environment:
          NPM_CONFIG_COLOR: false
    steps:
      - checkout
      - run: npm install
      - run: npm test
